# Use an official lightweight Python image.
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /

# Copy the local code to the container
COPY . .

# Install the Python dependencies
RUN pip install --no-cache-dir fastapi uvicorn

# Specify the command to run on container start
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]
